# Generated by Django 3.0.4 on 2020-04-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.TextField()),
                ('catagory', models.TextField()),
                ('image', models.URLField()),
                ('kingdom', models.TextField()),
                ('phylum', models.TextField()),
                ('classs', models.TextField()),
                ('order', models.TextField()),
                ('family', models.TextField()),
                ('genus', models.TextField()),
                ('species', models.TextField()),
                ('s_species', models.TextField(blank=True)),
                ('typee', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Individuals',
            new_name='Individual',
        ),
        migrations.DeleteModel(
            name='Specimens',
        ),
        migrations.AlterField(
            model_name='check',
            name='checkin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='check',
            name='checkout',
            field=models.DateTimeField(),
        ),
    ]
