# Generated by Django 3.0.4 on 2020-04-26 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200425_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specimen',
            old_name='catagory',
            new_name='category',
        ),
    ]
