# Generated by Django 3.0.4 on 2020-04-26 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200425_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimen',
            name='typee',
        ),
    ]
