# Generated by Django 3.0.4 on 2020-04-28 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_specimen_typee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='specimen',
        ),
        migrations.AddField(
            model_name='individual',
            name='course',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='check',
            field=models.BooleanField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='check',
            name='checkin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='check',
            name='checkout',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='image',
            field=models.TextField(),
        ),
    ]
