# Generated by Django 3.0.4 on 2020-04-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200428_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimen',
            name='check',
        ),
    ]
