# Generated by Django 3.0.4 on 2020-04-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_individual_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='course',
        ),
        migrations.AlterField(
            model_name='check',
            name='checkin',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='checkout',
            field=models.DateField(auto_now_add=True),
        ),
    ]
